import '../model/halo_error_code.dart';

HaloErrorCode makeHaloErrorCode(String? value) {
  switch (value) {
    case 'OK':
      return HaloErrorCode.ok;
    case 'Declined':
      return HaloErrorCode.declined;
    case 'DeclinedOffline':
      return HaloErrorCode.declinedOffline;
    case 'SingleTapAndPin':
      return HaloErrorCode.singleTapAndPin;
    case 'Unauthorised':
      return HaloErrorCode.unauthorised;
    case 'Forbidden':
      return HaloErrorCode.forbidden;
    case 'InvalidApiKey':
      return HaloErrorCode.invalidApiKey;
    case 'InvalidJSON':
      return HaloErrorCode.invalidJSON;
    case 'InvalidRequest':
      return HaloErrorCode.invalidRequest;
    case 'BlockedUser':
      return HaloErrorCode.blockedUser;
    case 'RequestSignatureInvalid':
      return HaloErrorCode.requestSignatureInvalid;
    case 'RequestSignatureMissing':
      return HaloErrorCode.requestSignatureMissing;
    case 'DeviceKeyMissing':
      return HaloErrorCode.deviceKeyMissing;
    case 'DeviceKeyInvalid':
      return HaloErrorCode.deviceKeyInvalid;
    case 'ReplayedMessage':
      return HaloErrorCode.replayedMessage;
    case 'RequestSigningKeyMissing':
      return HaloErrorCode.requestEncryptionKeyMissing;
    case 'RequestSigningKeyInvalid':
      return HaloErrorCode.requestEncryptionKeyInvalid;
    case 'RequestEncryptionKeyMissing':
      return HaloErrorCode.requestEncryptionKeyMissing;
    case 'RequestEncryptionKeyInvalid':
      return HaloErrorCode.requestEncryptionKeyInvalid;
    case 'DeviceNotAttested':
      return HaloErrorCode.deviceNotAttested;
    case 'DeviceFailedAttestation':
      return HaloErrorCode.deviceFailedAttestation;
    case 'JWTInvalid':
      return HaloErrorCode.jwtInvalid;
    case 'JWTExpired':
      return HaloErrorCode.jwtExpired;
    case 'IdAlreadyExists':
      return HaloErrorCode.idAlreadyExists;
    case 'PhoneNumberNotVerified':
      return HaloErrorCode.phoneNumberNotVerified;
    case 'EmailNotVerified':
      return HaloErrorCode.emailNotVerified;
    case 'DataNotFound':
      return HaloErrorCode.dataNotFound;
    case 'TransactionDoesNotBelongToMerchant':
      return HaloErrorCode.transactionDoesNotBelongToMerchant;
    case 'DuplicateMerchantReference':
      return HaloErrorCode.duplicateMerchantReference;
    case 'ReceiptSignatureInvalid':
      return HaloErrorCode.receiptSignatureInvalid;
    case 'InvalidAlgorithm':
      return HaloErrorCode.invalidAlgorithm;
    case 'SiteIndentifierInvalid':
      return HaloErrorCode.siteIdentifierInvalid;
    case 'SiteIdentifierMissing':
      return HaloErrorCode.siteIdentifierMissing;
    case 'ErrorWithExternalRequest':
      return HaloErrorCode.errorWithExternalRequest;
    case 'IntegratorNotApproved':
      return HaloErrorCode.integratorNotApproved;
    case 'DataError':
      return HaloErrorCode.dataError;
    case 'UserInvalid':
      return HaloErrorCode.userInvalid;
    case 'UnknownDeviceInstallationId':
      return HaloErrorCode.unknownDeviceInstallationId;
    case 'RequestEncryptionUnsupportedCurve':
      return HaloErrorCode.requestEncryptionUnsupportedCurve;
    case 'BlockedDevice':
      return HaloErrorCode.blockedDevice;
    case 'DatabaseIntegrityFailed':
      return HaloErrorCode.databaseIntegrityFailed;
    case 'DatabaseError':
      return HaloErrorCode.databaseError;
    case 'DecryptRequestError':
      return HaloErrorCode.decryptRequestError;
    case 'UnknownError':
      return HaloErrorCode.unknownError;
    case 'CryptoError':
      return HaloErrorCode.cryptoError;
    case 'DukputTransactionCounterOverflow':
      return HaloErrorCode.dukputTransactionCounterOverflow;
    case 'InvalidPaymentProvider':
      return HaloErrorCode.invalidPaymentProvider;
    case 'DeclinedByPaymentProvider':
      return HaloErrorCode.declinedByPaymentProvider;
    case 'FailedToSubmitToAllPaymentProviders':
      return HaloErrorCode.failedToSubmitToAllPaymentProviders;
    case 'InvalidPinData':
      return HaloErrorCode.invalidPinData;
    case 'RefundTooLate':
      return HaloErrorCode.refundTooLate;
    case 'RefundAlreadyProcessed':
      return HaloErrorCode.refundAlreadyProcessed;
    case 'MissingPfsServerKey':
      return HaloErrorCode.missingPfsServerKey;
    case 'NFCDisabled':
      return HaloErrorCode.nfcDisabled;
    case 'InvalidSystemState':
      return HaloErrorCode.invalidSystemState;
    case 'InvalidCurrency':
      return HaloErrorCode.invalidCurrency;
    case 'InvalidAndroidVersion':
      return HaloErrorCode.invalidAndroidVersion;
    case 'ErrorParsingJWT':
      return HaloErrorCode.errorParsingJWT;
    case 'NetworkError':
      return HaloErrorCode.networkError;
    case 'ResponseSignatureMissing':
      return HaloErrorCode.responseSignatureMissing;
    case 'ResponseSignatureInvalid':
      return HaloErrorCode.responseSignatureInvalid;
    case 'ServerRequestedConfigClear':
      return HaloErrorCode.serverRequestedConfigClear;
    case 'ErrorDeserialising':
      return HaloErrorCode.errorDeserialising;
    case 'SafetyNetAttestationError':
      return HaloErrorCode.safetyNetAttestationError;
    case 'GooglePlayUnavailable':
      return HaloErrorCode.googlePlayUnavailable;
    case 'TimeDriftTooGreat':
      return HaloErrorCode.timeDriftTooGreat;
    case 'AttestationInProgress':
      return HaloErrorCode.attestationInProgress;
    case 'RootedDevice':
      return HaloErrorCode.rootedDevice;
    case 'InstrumentedDevice':
      return HaloErrorCode.instrumentedDevice;
    case 'DebuggedDevice':
      return HaloErrorCode.debuggedDevice;
    case 'CancelledTransaction':
      return HaloErrorCode.cancelledTransaction;
    case 'CardTapTimeoutExpired':
      return HaloErrorCode.cardTapTimeoutExpired;
    case 'TransactionError':
      return HaloErrorCode.transactionError;
    case 'TEEAttestationError':
      return HaloErrorCode.teeAttestationError;
    case 'ErrorValidatingPinKey':
      return HaloErrorCode.errorValidatingPinKey;
    case 'IntegrityCheckFailed':
      return HaloErrorCode.integrityCheckFailed;
    case 'UseOfNfcStateBeforeConnect':
      return HaloErrorCode.useOfNfcStateBeforeConnect;
    case 'FailedToImportServerSigningCert':
      return HaloErrorCode.failedToImportServerSigningCert;
    case 'FailedToImportServerEncryptionKey':
      return HaloErrorCode.failedToImportServerEncryptionKey;
    case 'NotImplemented':
      return HaloErrorCode.notImplemented;
    case 'MissingSensors':
      return HaloErrorCode.missingSensors;
    case 'MicrophoneWasUnmuted':
      return HaloErrorCode.microphoneWasUnmuted;
    case 'NullAttestationHandle':
      return HaloErrorCode.nullAttestationHandle;
    case 'CryptographyError':
      return HaloErrorCode.cryptographyError;
    case 'SystemNotInitialised':
      return HaloErrorCode.systemNotInitialised;
    case 'CameraPermissionNotGranted':
      return HaloErrorCode.cameraPermissionNotGranted;
    case 'AccessibilityServiceBlocksPin':
      return HaloErrorCode.accessibilityServiceBlocksPin;
    case 'DeveloperOptionsEnabled':
      return HaloErrorCode.developerOptionsEnabled;
    case 'MissingAttestationNonce':
      return HaloErrorCode.missingAttestationNonce;
    case 'ConfigFetchError':
      return HaloErrorCode.configFetchError;
    case 'MissingEntropy':
      return HaloErrorCode.missingEntropy;
    case 'InvalidTransactionReference':
      return HaloErrorCode.invalidTransactionReference;
    case 'MissingSecureCardReaderImplementation':
      return HaloErrorCode.missingSecureCardReaderImplementation;
    case 'FailedToGetRandomBytes':
      return HaloErrorCode.failedToGetRandomBytes;
    case 'MissingDataKek':
      return HaloErrorCode.missingDataKek;
    case 'PinError':
      return HaloErrorCode.pinError;
    case 'BluetoothConnectPermissionsNotGranted':
      return HaloErrorCode.bluetoothConnectPermissionsNotGranted;
    case 'BluetoothScanPermissionNotGranted':
      return HaloErrorCode.bluetoothScanPermissionNotGranted;
    case 'BluetoothUnavailable':
      return HaloErrorCode.bluetoothUnavailable;
    case 'BluetoothScanInProgress':
      return HaloErrorCode.bluetoothScanInProgress;
    case 'BluetoothPairFailed':
      return HaloErrorCode.bluetoothPairFailed;
    case 'SecureCardReaderCommandFailed':
      return HaloErrorCode.secureCardReaderCommandFailed;
    case 'BluetoothDeviceUnavailable':
      return HaloErrorCode.bluetoothDeviceUnavailable;
    case 'SecureCardReaderTimeout':
      return HaloErrorCode.secureCardReaderTimeout;
    case 'SecureCardReaderConfigInvalid':
      return HaloErrorCode.secureCardReaderConfigInvalid;
    case 'BluetoothNotEnabled':
      return HaloErrorCode.bluetoothNotEnabled;
    case 'SecureCardReaderPinError':
      return HaloErrorCode.secureCardReaderPinError;
    case 'SecureCardReaderPluginNotAvailableForDevice':
      return HaloErrorCode.secureCardReaderPluginNotAvailableForDevice;
    case 'SecureCardReaderTransactionInProgress':
      return HaloErrorCode.secureCardReaderTransactionInProgress;
    case 'BluetoothFineLocationPermissionsNotGranted':
      return HaloErrorCode.bluetoothFineLocationPermissionsNotGranted;
    case 'BluetoothPairTimeout':
      return HaloErrorCode.bluetoothPairTimeout;
    default:
      throw Exception('Unknown HaloErrorCode value: $value');
  }
}
