rootProject.name = 'HaloRNExample'
apply from: file("../node_modules/@react-native-community/cli-platform-android/native_modules.gradle"); applyNativeModulesSettingsGradle(settings)
include ':app'
includeBuild('../node_modules/@react-native/gradle-plugin')

// Halo SDK React Native plugin (local source to matche npm package name)
include ':halo-sdk-react-native'
project(':halo-sdk-react-native').projectDir = new File(rootDir, '../../../plugins/react-native/android')

